version: '3.6'
# Coba cek ga pakai links masih bisa atau engga
services:
  nginx:
    image: 'nginx:latest'
    links:
      - server
      - client
    volumes:
      - ./client:/var/www/html
      # - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8001:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - './server:/usr/local/application'
      - '/usr/local/application/node_modules'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/var/www/html'
      - '/var/www/html/node_modules'
  client_dev:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/var/www/html'
      - '/var/www/html/node_modules'
    ports:
      - '3002:3000'
    command: ['npm', 'run', 'start']
